language: php
php:
  - 7.1
before_script:
  - composer install --dev
script:
  - vendor/bin/phpunit --coverage-clover=build/log/clover.xml
  - make stan
  - make cs
after_success:
  - travis_retry php vendor/bin/coveralls -v
notifications:
  slack:
    secure: iKHq3Cf5mlvpwyKag0u9r7wzuMI1KxBBgG0bo16yWm4G3E3gLT+W6lKPX6ZnxK690AincLDbpaZd6iNDebJz1wIoGX2jXmBfYgTIQWWrGiIOool6QJsj6FFaIdsTyAZwz6fusgY6g/Sweplqbchldw+CKliG3SBYp4KQwsyC1ZBxXbfarNvCYIhZffsi2ApbWhc/GfE20R3wSVr5TvNshsCp/RBRhhUdl8M1pt2BcCqdWwzhxJd+Yh3r2qbUKAdAClpxfozGQzlu/BxlO2+jhuX4aHUgcfC1eqY0FJC7TA63UsS1CtUt/NeXb8rPBfLr+SPsHbsVnkQFYkU4qGLs+2MAEtFcDwS8E30i3J5LE8GODhnr3PoxKAD6vgZ2tSeWlYXWS33ym6HWpurxOQX6icmzjVD1Ca0CwUvknX2UrPy6n2kZC0Uq/2YYi5BG0I+u5JVlgD8+PD/OgvG3xq98LoW/JOx/bGD3y/XnCKZsiLWtUNEj7B1kcGQRWfc6pyA5NtavLsZsODwya2r64ytimiadqJyZw1hLgrCKVhUqAxWtaWxJaf3r0iP8mXGWmf2IjejuhqXDpOMtHI1qyw+WQlrRbTSklCANtifK8cY14iAtwXg02AhcdG/ncCodNawMep7W6OWo4tUL677/XJejdngNRNXVrtwUgAfv/5NulJY=
